services:
  loadbalance:
    image: nginx:1.25.2-alpine
    container_name: loadbalance
    ports:
      - "8080:80"
  node1:
    image: nginx:1.25.2-alpine
    container_name: node1
    volumes:
      - "/home/euridyce/aehmotor-frontend-dev/dist:/usr/share/nginx/html"
  node2:
    image: nginx:1.25.2-alpine
    container_name: node2
    volumes:
      - "/home/euridyce/aehmotor-frontend-dev/dist:/usr/share/nginx/html"
  node3:
    image: nginx:1.25.2-alpine
    container_name: node3
    volumes:
      - "/home/euridyce/aehmotor-frontend-dev/dist:/usr/share/nginx/html"
